services:
  - type: web
    name: stock-analyzer
    runtime: node
    repo: https://github.com/CHAVKVK2/stock-analyzer
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: FINNHUB_API_KEY
        sync: false
